"""
Security module tests.

These tests verify that the security utilities correctly:
1. Block path traversal attempts
2. Allow valid paths within the repository
3. Skip binary and lock files
4. Skip oversized files
5. Block unauthorized test commands

Each test includes comments explaining what security property is being verified.
"""

import os
import tempfile
from pathlib import Path

import pytest

from reforge_mcp.utils.security import (
    SecurityError,
    should_skip_file,
    validate_path,
    validate_test_command,
)


class TestValidatePath:
    """Tests for path validation and traversal prevention."""

    def test_path_traversal_blocked(self, tmp_path: Path) -> None:
        """
        Verify that path traversal attempts are blocked.

        SECURITY PROPERTY: An attacker cannot use "../" sequences to escape
        the repository root and access arbitrary filesystem paths.
        """
        repo_root = tmp_path / "repo"
        repo_root.mkdir()

        # Create a file outside the repo
        outside_file = tmp_path / "secret.txt"
        outside_file.write_text("secret data")

        # Attempt to access the file via path traversal
        malicious_path = repo_root / ".." / "secret.txt"

        with pytest.raises(SecurityError) as exc_info:
            validate_path(str(malicious_path), str(repo_root))

        assert "Path traversal blocked" in str(exc_info.value)
        assert "outside the repository root" in str(exc_info.value)

    def test_valid_path_allowed(self, tmp_path: Path) -> None:
        """
        Verify that legitimate paths within the repo are allowed.

        SECURITY PROPERTY: Valid operations are not impeded - security
        should be invisible to legitimate use.
        """
        repo_root = tmp_path / "repo"
        repo_root.mkdir()

        # Create a valid file inside the repo
        valid_file = repo_root / "src" / "main.py"
        valid_file.parent.mkdir(parents=True)
        valid_file.write_text("print('hello')")

        # This should not raise
        result = validate_path(str(valid_file), str(repo_root))

        assert result.is_absolute()
        assert result.name == "main.py"
        assert "src" in str(result)

    def test_symlink_to_outside_blocked(self, tmp_path: Path) -> None:
        """
        Verify that symlinks pointing outside the repo are blocked.

        SECURITY PROPERTY: Symlinks cannot be used to bypass path validation.
        This is why we use resolve() - it follows symlinks to their target.
        """
        repo_root = tmp_path / "repo"
        repo_root.mkdir()

        # Create a file outside the repo
        outside_file = tmp_path / "outside.txt"
        outside_file.write_text("outside data")

        # Create a symlink inside repo pointing outside
        symlink_path = repo_root / "link.txt"
        symlink_path.symlink_to(outside_file)

        with pytest.raises(SecurityError) as exc_info:
            validate_path(str(symlink_path), str(repo_root))

        assert "Path traversal blocked" in str(exc_info.value)

    def test_absolute_path_outside_blocked(self, tmp_path: Path) -> None:
        """
        Verify that absolute paths outside repo are blocked.

        SECURITY PROPERTY: Using an absolute path directly does not bypass
        the security check.
        """
        repo_root = tmp_path / "repo"
        repo_root.mkdir()

        # Try to access /etc/passwd or similar
        with pytest.raises(SecurityError) as exc_info:
            validate_path("/etc/passwd", str(repo_root))

        assert "Path traversal blocked" in str(exc_info.value)


class TestShouldSkipFile:
    """Tests for file skip logic."""

    def test_binary_file_skipped(self, tmp_path: Path) -> None:
        """
        Verify that binary files are skipped.

        SECURITY PROPERTY: Binary files (images, executables) are not
        processed by the MCP server, which is designed for code analysis.
        """
        binary_file = tmp_path / "image.png"
        binary_file.write_bytes(b"\x89PNG\r\n\x1a\n")

        assert should_skip_file(binary_file) is True

    def test_lock_file_skipped(self, tmp_path: Path) -> None:
        """
        Verify that lock files are skipped.

        SECURITY PROPERTY: Lock files are auto-generated by package managers
        and should never be manually modified.
        """
        lock_file = tmp_path / "package-lock.json"
        lock_file.write_text("{}")

        assert should_skip_file(lock_file) is True

    def test_minified_file_skipped(self, tmp_path: Path) -> None:
        """
        Verify that minified files are skipped.

        SECURITY PROPERTY: Minified files are build artifacts. Modifying
        them directly would be overwritten on next build.
        """
        minified_file = tmp_path / "bundle.min.js"
        minified_file.write_text("var a=1;")

        assert should_skip_file(minified_file) is True

    def test_oversized_file_skipped(self, tmp_path: Path) -> None:
        """
        Verify that oversized files are skipped.

        SECURITY PROPERTY: Large files could be database dumps, logs, or
        other non-code data. Also protects against memory exhaustion.
        """
        large_file = tmp_path / "large.txt"
        # Create a file larger than 500KB (default limit)
        large_file.write_bytes(b"x" * (501 * 1024))

        assert should_skip_file(large_file) is True

    def test_valid_source_file_not_skipped(self, tmp_path: Path) -> None:
        """
        Verify that legitimate source files are not skipped.

        SECURITY PROPERTY: Security should be invisible to legitimate use -
        normal source files should process without interference.
        """
        source_file = tmp_path / "main.py"
        source_file.write_text("def main(): pass")

        assert should_skip_file(source_file) is False

    def test_pycache_file_skipped(self, tmp_path: Path) -> None:
        """
        Verify that Python bytecode files are skipped.

        SECURITY PROPERTY: Bytecode files are auto-generated and should
        not be analyzed or modified.
        """
        pyc_file = tmp_path / "module.pyc"
        pyc_file.write_bytes(b"\x00\x00\x00\x00")

        assert should_skip_file(pyc_file) is True


class TestValidateTestCommand:
    """Tests for test command validation."""

    def test_allowed_command_passes(self) -> None:
        """
        Verify that allowed commands pass validation.

        SECURITY PROPERTY: Legitimate test commands work without friction.
        """
        result = validate_test_command("pytest tests/", ["pytest", "tox"])
        assert result is True

    def test_blocked_command_raises_error(self) -> None:
        """
        Verify that non-allowlisted commands are blocked.

        SECURITY PROPERTY: Commands not in the allowlist cannot be executed,
        preventing arbitrary command injection.
        """
        with pytest.raises(SecurityError) as exc_info:
            validate_test_command("rm -rf /", ["pytest", "tox"])

        assert "Command blocked" in str(exc_info.value)
        assert "not in the allowlist" in str(exc_info.value)

    def test_command_injection_blocked_semicolon(self) -> None:
        """
        Verify that command injection via semicolon is blocked.

        SECURITY PROPERTY: Attackers cannot chain malicious commands after
        a legitimate-looking command using shell operators.
        """
        with pytest.raises(SecurityError) as exc_info:
            validate_test_command("pytest; rm -rf /", ["pytest"])

        assert "Command injection blocked" in str(exc_info.value)
        assert ";" in str(exc_info.value)

    def test_command_injection_blocked_pipe(self) -> None:
        """
        Verify that command injection via pipe is blocked.

        SECURITY PROPERTY: Piping output to another command is a common
        injection technique and must be blocked.
        """
        with pytest.raises(SecurityError) as exc_info:
            validate_test_command("pytest | cat /etc/passwd", ["pytest"])

        assert "Command injection blocked" in str(exc_info.value)

    def test_command_injection_blocked_backticks(self) -> None:
        """
        Verify that command injection via backticks is blocked.

        SECURITY PROPERTY: Backtick command substitution is a dangerous
        injection vector that must be blocked.
        """
        with pytest.raises(SecurityError) as exc_info:
            validate_test_command("pytest `whoami`", ["pytest"])

        assert "Command injection blocked" in str(exc_info.value)

    def test_command_injection_blocked_dollar_paren(self) -> None:
        """
        Verify that command injection via $() is blocked.

        SECURITY PROPERTY: $() command substitution is the modern form of
        command injection and must be blocked.
        """
        with pytest.raises(SecurityError) as exc_info:
            validate_test_command("pytest $(cat /etc/passwd)", ["pytest"])

        assert "Command injection blocked" in str(exc_info.value)

    def test_empty_command_blocked(self) -> None:
        """
        Verify that empty commands are blocked.

        SECURITY PROPERTY: Empty or whitespace-only commands should not
        be executed, as they indicate a configuration error or attack.
        """
        with pytest.raises(SecurityError) as exc_info:
            validate_test_command("", ["pytest"])

        assert "Empty command" in str(exc_info.value)

    def test_command_with_args_allowed(self) -> None:
        """
        Verify that allowed commands with arguments pass.

        SECURITY PROPERTY: Commands with legitimate arguments work -
        we check prefix matching, not exact equality.
        """
        result = validate_test_command(
            "pytest tests/ -v --cov=src",
            ["pytest"]
        )
        assert result is True


class TestSecurityError:
    """Tests for the SecurityError exception."""

    def test_security_error_message(self) -> None:
        """
        Verify that SecurityError preserves error messages.

        SECURITY PROPERTY: Security errors should provide clear feedback
        about what was blocked and why, aiding in learning and debugging.
        """
        error = SecurityError("Test security violation")
        assert str(error) == "Test security violation"

    def test_security_error_is_exception(self) -> None:
        """
        Verify that SecurityError is properly catchable as Exception.

        SECURITY PROPERTY: SecurityError must be an Exception subclass
        so it can be caught and handled appropriately.
        """
        assert isinstance(SecurityError("test"), Exception)
