"""
Security utilities for Reforge MCP.

This module provides three critical security functions that protect against:
1. Path traversal attacks (accessing files outside the repo)
2. Processing unsafe file types (binaries, locks, oversized files)
3. Command injection via test commands

Each function includes detailed error messages to help users understand
what was blocked and why - this is a learning project, so the "why" matters.
"""

from pathlib import Path
from typing import Any


class SecurityError(Exception):
    """
    Custom exception for security violations.

    Why a custom exception:
    - Makes security errors explicit and easy to catch
    - Allows callers to distinguish security failures from other errors
    - Provides a clear signal that something potentially malicious was attempted
    """

    pass


def validate_path(path: str, repo_root: str) -> Path:
    """
    Validate that a path is safely within the repository root.

    PROTECTS AGAINST:
    - Path traversal attacks (e.g., "../../../etc/passwd")
    - Symlink attacks (symlinks pointing outside repo)
    - Absolute path escapes (e.g., "/etc/passwd" when repo is /home/user/project)

    HOW IT WORKS:
    1. Resolves both paths to their absolute, canonical forms
    2. Checks if the resolved path starts with the repo root
    3. Raises SecurityError if the path escapes the repository

    Why resolve() matters:
    - Converts relative paths to absolute: "src/main.py" → "/repo/src/main.py"
    - Follows symlinks to their real destination
    - Normalizes path components: "/repo/foo/../bar" → "/repo/bar"
    - Without this, attackers could use ".." or symlinks to escape

    Args:
        path: The path to validate (can be relative or absolute)
        repo_root: The repository root directory (must be absolute)

    Returns:
        The resolved Path object if validation passes

    Raises:
        SecurityError: If the resolved path is outside repo_root

    Example:
        >>> validate_path("src/main.py", "/home/user/myproject")
        PosixPath('/home/user/myproject/src/main.py')

        >>> validate_path("../../etc/passwd", "/home/user/myproject")
        SecurityError: Path traversal blocked: '/etc/passwd' is outside '/home/user/myproject'
    """
    try:
        repo_root_resolved = Path(repo_root).resolve()
        path_resolved = Path(path).resolve()
    except (OSError, ValueError) as e:
        raise SecurityError(
            f"Invalid path: cannot resolve '{path}' - {e}"
        ) from e

    # Check if path_resolved is within repo_root_resolved
    # We use is_relative_to() which is cleaner than manual prefix checking
    try:
        path_resolved.relative_to(repo_root_resolved)
    except ValueError:
        # Path is outside repo_root - this is a security violation
        raise SecurityError(
            f"Path traversal blocked: '{path}' resolves to '{path_resolved}' "
            f"which is outside the repository root '{repo_root_resolved}'. "
            f"This could indicate an attempt to access files outside the repository."
        )

    return path_resolved


def should_skip_file(
    path: Path,
    max_file_size_kb: int = 500,
    skip_extensions: set[str] | None = None,
    skip_filenames: set[str] | None = None,
) -> bool:
    """
    Determine if a file should be skipped during processing.

    PROTECTS AGAINST:
    - Processing binary files that could be malformed or malicious
    - Wasting resources on generated/lock files that shouldn't be modified
    - Memory exhaustion from oversized files
    - Accidentally modifying dependency lock files

    WHY SKIP THESE FILES:
    1. Binary files (.png, .exe, etc.): Not human-readable, could contain
       malicious payloads, and the MCP server is designed for code analysis.

    2. Lock files (package-lock.json, yarn.lock, etc.): Auto-generated by
       package managers. Modifying them manually breaks dependency resolution.

    3. Minified files (.min.js): Auto-generated from source files. Changes
       would be overwritten on next build.

    4. Oversized files: Could be database dumps, logs, or other data files
       that aren't code. Also protects against memory exhaustion attacks.

    Args:
        path: Path to the file to check
        max_file_size_kb: Maximum file size in KB (default 500KB from reforge.toml)
        skip_extensions: Set of extensions to skip (default: common binaries/locks)
        skip_filenames: Set of filenames to skip (default: lock files)

    Returns:
        True if the file should be skipped, False if safe to process

    Example:
        >>> should_skip_file(Path("node_modules/jquery.min.js"))
        True

        >>> should_skip_file(Path("src/main.py"))
        False
    """
    # Default extensions to skip - binaries, locks, minified files, assets
    if skip_extensions is None:
        skip_extensions = {
            # Minified and lock files
            ".min.js",
            ".lock",
            # Binary/executable formats
            ".bin",
            ".exe",
            # Source maps (auto-generated)
            ".map",
            # Image formats
            ".png",
            ".jpg",
            ".jpeg",
            ".gif",
            ".woff",
            ".woff2",
            ".ttf",
            ".ico",
            # Document formats
            ".pdf",
            # Archive formats
            ".zip",
            ".tar",
            ".gz",
            # Python bytecode
            ".pyc",
        }

    # Default filenames to skip - all lock files
    if skip_filenames is None:
        skip_filenames = {
            "package-lock.json",
            "yarn.lock",
            "poetry.lock",
            "Pipfile.lock",
            "composer.lock",
        }

    # Check filename against skip list
    if path.name in skip_filenames:
        return True

    # Check extension - need to handle compound extensions like .min.js
    suffix = path.suffix.lower()
    # For compound extensions, check the full suffix chain
    full_suffix = "".join(path.suffixes).lower()

    for skip_ext in skip_extensions:
        if full_suffix.endswith(skip_ext) or suffix == skip_ext:
            return True

    # Check file size if the file exists
    try:
        file_size_kb = path.stat().st_size / 1024
        if file_size_kb > max_file_size_kb:
            return True
    except (OSError, FileNotFoundError):
        # If we can't stat the file, skip it to be safe
        return True

    return False


def validate_test_command(command: str, allowed_commands: list[str]) -> bool:
    """
    Validate that a test command is in the allowlist.

    PROTECTS AGAINST:
    - Command injection attacks (e.g., "pytest; rm -rf /")
    - Shell injection via malicious test commands
    - Accidental execution of unintended commands

    WHY COMMAND VALIDATION MATTERS:
    The MCP server may run test commands after applying fixes. Without
    validation, an attacker could inject arbitrary shell commands through
    a malicious reforge.toml configuration or user input.

    HOW IT WORKS:
    1. Strips leading/trailing whitespace
    2. Checks if the command starts with an allowed command
    3. Allows arguments but blocks command chaining (via ;, &&, ||, |)

    SECURITY NOTE:
    We check if the command STARTS WITH an allowed command to permit
    arguments (e.g., "pytest tests/" is allowed if "pytest" is in the
    allowlist). However, we block command chaining operators.

    Args:
        command: The command to validate
        allowed_commands: List of allowed command prefixes

    Returns:
        True if the command is allowed

    Raises:
        SecurityError: If the command is not in the allowlist or contains
                      dangerous operators

    Example:
        >>> validate_test_command("pytest tests/", ["pytest", "tox"])
        True

        >>> validate_test_command("pytest; rm -rf /", ["pytest"])
        SecurityError: Command injection blocked: 'pytest; rm -rf /' contains dangerous operator ';'
    """
    if not command or not command.strip():
        raise SecurityError(
            "Empty command: test command cannot be empty"
        )

    command_stripped = command.strip()

    # Check for command chaining operators - these enable injection
    dangerous_operators = [";", "&&", "||", "|", "`", "$(",]
    for op in dangerous_operators:
        if op in command_stripped:
            raise SecurityError(
                f"Command injection blocked: '{command_stripped}' contains "
                f"dangerous operator '{op}'. Only single commands are allowed."
            )

    # Check if command starts with an allowed command
    for allowed in allowed_commands:
        if command_stripped.startswith(allowed):
            return True

    # Command not in allowlist
    raise SecurityError(
        f"Command blocked: '{command_stripped}' is not in the allowlist. "
        f"Allowed commands: {', '.join(repr(cmd) for cmd in allowed_commands)}. "
        f"This prevents arbitrary command execution."
    )

    return True
